name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "Friendtaliy"
        git config --global user.email "Friendtaliy@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |

        git config --global --unset http.proxy
        git config --global --unset https.proxy
        git add -A
        git commit -a -m "Hello"
        git push -f
